#配置数据源
spring:
  datasource:
    url: jdbc:mysql://39.106.121.52:3306/community_feature1?useUnicode=true&characterEncoding=utf-8
    username: root
    password: mz666
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 8
      minIdle: 1
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x' FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      max-open-prepared-statements: 20
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false





# 配置tomcat端口
server:
  port: 8088
  servlet:
    context-path: /community

# 配置打印输出sql日志
logging:
  level:
    com.muchi.community.dict.mapper : debug
    com.muchi.community.user.mapper : debug
    com.muchi.community.message.mapper : debug
    com.muchi.community.shiro.dao : debug

debug: false


fdfs:
  connect-timeout: 1500 #socket连接时间
  so-timeout: 1500 #连接tracker服务器超时
  pool:
    max-total: 150
    max-wait-millis: 100
    #缩略图尺寸
  thumb-image:
    width: 150
    height: 150
#  tracker-list: 192.168.1.188:22122
#  web-server-url: http://192.168.1.188/
  tracker-list: 39.106.121.52:22122
  web-server-url: http://39.106.121.52/

